version: '3'

services:
  notebook:
    build: ./docker/.

    # ports:
    #   - "127.0.0.1:8888:8888"

    network_mode: "host"   # so we will be able to make requests

    hostname: "localhost"

    env_file:
      - notebooks.env

    volumes:
      - .:/app