# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sp500.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bsp500.proto\" \n\x0fSearchRequestSP\x12\r\n\x05query\x18\x01 \x01(\t\"\x93\x01\n\x07\x43ompany\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0e\n\x06ticker\x18\x02 \x01(\t\x12\x13\n\x0b\x66irst_added\x18\x03 \x01(\t\x12\x17\n\x0fyear_foundation\x18\x04 \x01(\x05\x1a.\n\x06Sector\x12\x11\n\tprincipal\x18\x01 \x01(\t\x12\x11\n\tsecondary\x18\x02 \x01(\tB\x07\n\x05_name\"-\n\x10SearchResponseSP\x12\x19\n\x07\x63ompany\x18\x01 \x03(\x0b\x32\x08.Company2\xc2\x02\n\x0cListSearchSP\x12\x38\n\x0fListCompaniesSP\x12\x10.SearchRequestSP\x1a\x11.SearchResponseSP\"\x00\x12N\n#ListCompaniesSPStreamSingleResponse\x12\x10.SearchRequestSP\x1a\x11.SearchResponseSP\"\x00(\x01\x12O\n$ListCompaniesSPRequestStreamResponse\x12\x10.SearchRequestSP\x1a\x11.SearchResponseSP\"\x00\x30\x01\x12W\n*ListCompaniesSPStreamRequestStreamResponse\x12\x10.SearchRequestSP\x1a\x11.SearchResponseSP\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sp500_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEARCHREQUESTSP._serialized_start=15
  _SEARCHREQUESTSP._serialized_end=47
  _COMPANY._serialized_start=50
  _COMPANY._serialized_end=197
  _COMPANY_SECTOR._serialized_start=142
  _COMPANY_SECTOR._serialized_end=188
  _SEARCHRESPONSESP._serialized_start=199
  _SEARCHRESPONSESP._serialized_end=244
  _LISTSEARCHSP._serialized_start=247
  _LISTSEARCHSP._serialized_end=569
# @@protoc_insertion_point(module_scope)
